### ISSUE TITLE
Logger injection issue

### ISSUE THREAD

**Issue by avaneszdes** [ernado-x/X.Extensions.Logging.Telegram#18]
#### Description

I went through all the steps to configure the dependencies.
When I run my application I got an exception:

`System.MissingMethodException: Method not found: 'Void Telegram.Bot.TelegramBotClient..ctor(System.String, System.Net.Http.HttpClient, System.String)'.
   at X.Extensions.Logging.Telegram.TelegramLogWriter..ctor(String accessToken, String chatId)
   at X.Extensions.Logging.Telegram.TelegramLoggerExtensions.AddTelegram(ILoggingBuilder builder, TelegramLoggerOptions options)
   at X.Extensions.Logging.Telegram.TelegramLoggerExtensions.AddTelegram(ILoggingBuilder builder, IConfiguration configuration)
   at Program.<Main>$(String[] args) in C:\Users\avane\RiderProjects\api\src\LingoPractices.Api\Program.cs:line 39`

I tried to add this project as project to my solution and this case works perfectly, but as nuget package does not.

#### Screenshots
Exception:

![image](https://user-images.githubusercontent.com/54480719/222944270-ce8b0724-81c4-45cd-9e80-740619aa436b.png)

appsettings.json logger configuration

![image](https://user-images.githubusercontent.com/54480719/222944371-f689917f-1a36-4a36-ad70-a0569cf1e8f1.png)

**Comment by ernado-x** [comment]
What version of .NET are you using?

Have you tried running the examples from this repository?

**Comment by avaneszdes** [comment]
1) I use .NET 7
2) Yes, I have tried and it works as we expect.

**Comment by avaneszdes** [comment]
Looks like the issue is fixed, thanks!
