### ISSUE TITLE
Bad Request: message thread not found

### ISSUE THREAD

**Issue by vermilion** [ernado-x/X.Extensions.Logging.Telegram#52]
After upgrade to **1.0.7** I get following exception

```
Bad Request: message thread not found

   at Telegram.Bot.TelegramBotClient.<MakeRequestAsync>d__21`1.MoveNext()
   at Telegram.Bot.TelegramBotClientExtensions.<SendTextMessageAsync>d__7.MoveNext()
   at X.Extensions.Logging.Telegram.TelegramLogWriter.<Write>d__5.MoveNext() in D:\mosreg\roadmaps\X.Extensions.Logging.Telegram\TelegramLogWriter.cs:line 45
```

Seems like this is caused by new overload of `SendTextMessageAsync` introduced in `Telegram.Bot v19`

**Comment by ernado-x** [comment]
Please checkout [version 2.0](https://www.nuget.org/packages/X.Extensions.Logging.Telegram/2.0.0-beta) (currently in beta). On my local tests it working fine.

Also I want to mention that new version we develop together with @Bardin08 in this [fork](https://github.com/dncuug/X.Extensions.Logging.Telegram).

**Comment by ernado-x** [comment]
Please reopen issue if it is still actual
